version: '3.8'

services:
  data-dashboard:
    build: .
    container_name: data_viz_app
    ports:
      - "8000:8000"
    volumes:
      # This allows you to edit code locally and see changes in container
      - ./backend:/app/backend
      - ./frontend:/app/frontend